INSERT OR IGNORE INTO Teachers (code, name, subject) VALUES
("A1","Muslicha, M.Pd.","PPKN"),
("A2","Bibit Purwantini, M.Pd.","PPKN"),
("B0","Drs. Ubaidillah, M.Pd.","Pend. Agama"),
("B1","Rumada, S.PAK., M.Pd.","Pend. Agama"),
("B2","Henny Bibinur Baniah, M.Pd.","Pend. Agama"),
("B3","Saifudin, S.SI, M.Pd.","Pend. Agama"),
("B4","Abdul Salim, M.Pd.","Pend. Agama"),
("B5","Oktavianus, S.S.","Pend. Agama"),
("C1","H. Edy Pramono, S.Pd.","Bahasa Indonesia"),
("C2","Nursiti Kamsiati, S.Pd.","Bahasa Indonesia"),
("C3","Niken Meilina Putri, S.Pd.","Bahasa Indonesia"),
("D1","Uswatun Hasanah, S.Pd.","Sejarah"),
("D2","Ari Sulastri, S.Pd.","Sejarah"),
("E1","Drs. Eko Rahardjo, M.M.","Bahasa Inggris"),
("E2","Muhammad Fajar, S.Pd.","Bahasa Inggris"),
("E3","Aulia Belfa Muthia, S.Pd.","Bahasa Inggris"),
("E4","Tedy Nurmansyah, S,.Pd.","Bahasa Inggris"),
("F1","Dr. Gatot Handoko, M.Pd.","PJOK"),
("F2","Bagus Cipta Asmauli, S.Pd.","PJOK"),
("F3","Bambang Triaji Asnoto, M.Pd.","PJOK"),
("G1","Swisma, S.Pd.","Matematika"),
("G2","Hari Wahyono, S.Pd.","Matematika"),
("G3","Fronika Munthe, S.Pd.","Matematika"),
("G4","Anggraini Pratiwi, S.Pd.","Matematika"),
("G5","Ahmad Syauqi, S.Si, M.Pd.","Matematika"),
("G6","Wawan Setiawan, S.Si, M.Stat.","Matematika"),
("H1","Drs. H. Yani Bayani, M,Pd.","Fisika"),
("H2","Joko Untoro, S.Pd.","Fisika"),
("H3","Fakhrizal Arsi, S.Pd.","Fisika"),
("H4","Hidayatun Nikmah, S.Pd.","Fisika"),
("I1","Yustrida Maisa, S.Pd, M.Si.","Biologi"),
("I2","Eti Sugiarti, S.Pd.","Biologi"),
("I3","Diva Rara Vidyani Maisa, S.Pd.","Biologi"),
("J1","Hj. Rina Gustini, M.Pd.","Kimia"),
("J2","Dwi Amelia Savitri, M.Pd.","Kimia"),
("J3","Jery Anderson Sitorus, S.Pd","Kimia"),
("J4","Rossy Lanasari, S.Pd.","Kimia"),
("K1","Evawati, S.Pd.","Ekonomi"),
("K2","Nuh Hudawi, S.Pd.","Ekonomi"),
("K3","Lilis Retno Rahayu, S.Pd.","Ekonomi"),
("L1","Haryono, S.Pd.","Sosiologi"),
("N1","Wangsa Jaya, M.Si.","Geografi"),
("N2","Erza Hermawan, S.Pd.","Geografi"),
("O1","Ahmad Jati, M.Pd.","Seni Budaya"),
("O2","Reza Fajrin Wijaya Kusuma, S.Pd.","Seni Budaya"),
("Q1","Ika Budianingsih, S.Pd.","Bimbingan Konseling"),
("Q2","Catur Rahmi Setiawati, S.Pd.","Bimbingan Konseling"),
("Q3","Dina Apriliyati, S.Pd.","Bimbingan Konseling"),
("Q4","Muhammad Sutrisno, S.Pd.","Bimbingan Konseling"),
("S1","Rocmuljati Ekasari Dawam, S.Pd.","Bahasa Jerman"),
("S2","Sri Rejeki, S.Pd.","Bahasa Jerman"),
("S3","Wurhandayani, S.Pd.","Bahasa Jerman"),
("T1","Khairunissa, S.T.","Informatika"),
("T2","Haerudi Yanshah, S.Kom, M.Pd.","Informatika"),
("T3","Prasojo, M.M.S.I.","Informatika"),
("PK1","Evawati, S.Pd.","PKWU"),
("PK2","Nuh Hudawi, S.Pd.","PKWU"),
("PK3","Dwi Amelia Savitri, M.Pd.","PKWU"),
("PK4","Hidayatun Nikmah, S.Pd.","PKWU"),
("PK5","Rossy Lanasari, S.Pd","PKWU"),
("X1","Upacara","Upacara"),
("X2","Istirahat","Istirahat"),
("X3","Selesai","Selesai"),
("X4","Tadarus / Doa Pagi","Tadarus / Doa Pagi"),
("X5","Kegiatan Kerohanian","Kegiatan Kerohanian"),
("Z0","EMPTY","EMPTY");